export const seedData = [
  { name: "Maya Patel", gender: "female" },
  { name: "Lucas Moreau", gender: "male" },
  { name: "Aisha Rahman", gender: "female" },
  { name: "Daniel Kim", gender: "male" },
  { name: "Sofia Rossi", gender: "female" },
  { name: "Ethan Brooks", gender: "male" },
  { name: "Isabella Costa", gender: "female" },
  { name: "Noah Fischer", gender: "male" },
  { name: "Priya Nair", gender: "female" },
  { name: "Oliver Bennett", gender: "male" },
  { name: "Elena Petrova", gender: "female" },
  { name: "Samuel Okoro", gender: "male" },
  { name: "Camila Ferreira", gender: "female" },
  { name: "Hugo Martins", gender: "male" },
  { name: "Yuki Tanaka", gender: "female" },
  { name: "Nathan Cooper", gender: "male" },
  { name: "Fatima Hassan", gender: "female" },
  { name: "Leo Dubois", gender: "male" },
  { name: "Ananya Sharma", gender: "female" },
  { name: "Mateo Silva", gender: "male" },
  { name: "Hannah Müller", gender: "female" },
  { name: "Victor Andersen", gender: "male" },
  { name: "Sara El Amrani", gender: "female" },
  { name: "Gabriel Novak", gender: "male" },
  { name: "Chloe Nguyen", gender: "female" },
  { name: "Benjamin Osei", gender: "male" },
  { name: "Lucia Romano", gender: "female" },
  { name: "Adrian Kowalski", gender: "male" },
  { name: "Emily Johnson", gender: "female" },
  { name: "Karim Haddad", gender: "male" },
];
